config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users
  
  
  get '/pages/home', to: 'pages#home'

  resources :users
  get '/signup', to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :projects
  resources :bugs


 
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bug.rb
class Bug < ApplicationRecord
    belongs_to :project

    

    belongs_to :bug_creator, class_name: "User", foreign_key: "creator_id"
    belongs_to :bug_assignee, class_name: "User", foreign_key: "assignee_id"


    enum bug_type: [:feature, :bug]
end

app/models/project.rb
class Project < ApplicationRecord
    
    has_many :user_projects
    has_many :users, through: :user_projects

    belongs_to :project_creator, class_name: "User", foreign_key: "creator_id"

    has_many :bugs     

end

app/models/user.rb
class User < ApplicationRecord
      

    has_many :user_projects
    has_many :projects, through: :user_projects

    has_many :created_projects, class_name: "Project", foreign_key: "creator_id"

    has_many :created_bugs, class_name: "Bug", foreign_key: "creator_id"
    has_many :assigned_bugs, class_name: "Bug", foreign_key: "assignee_id"




  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  
  enum role: [:qa, :manager, :developer,]
  

  
  
end

app/models/user_project.rb
class UserProject < ApplicationRecord
    belongs_to :user  
    belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :role])
  end
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
    def index
        @b = Bug.all
    end


    def show
        @b = Bug.find(params[:id])
    end

    def new 
        @b = Bug.new
    end 


    def create
        @b = Bug.new(project_params)
        @b.project_creator = User.last
        if @p.save
            flash[:success] = "project save successfully"
            redirect_to project_path(@p)
    
        else 
            render 'new'
        end  
    end 


    private
 
    def project_params
        params.require(:project).permit(:projectname, :description, :creator_id, :assignee_id)
        redirect_to projects_path
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home 
    end





end 

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    def index
        @p = Project.all
    end


    def show
        @p = Project.find(params[:id])
    end

    def new 
        @p = Project.new
    end 


    def create
        @p = Project.new(project_params)
        @p.creator_id = current_user.id
        if @p.save
            flash[:success] = "project save successfully"
            redirect_to projects_path
    
        else 
            render 'new'
        end  
    end 


    def edit  
        @p = Project.find(params[id])
    end 

    def update 
    end


    private
 
    def project_params
        params.require(:project).permit(:projectname, :description, :creator_id, :assignee_id)
        
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @q = User.where(role: 'qa')
        @d = User.where(role: 'developer')
        @m = User.where(role: 'manager')
        @usr = User.all
    end


    def show
        @usr = User.find(params[:id])
    end


    

end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bugs/_bug.html.erb
<div class="container">




<table class="table table-striped">
  <tr align="center">
     <th>Bug Name</th>
  </tr>
<% obj.each do |b|%>

  <tr align="center">
     <td><%= link_to b.title, bug_path(b), :class => "btn btn-outline-info"%></td>
  </tr>
  <% end %> 
</table>

    
    
 

</div>

app/views/bugs/_form.html.erb
<div class="container">
<%= bootstrap_form_for(@b, :html => {class: "form-horizontal", role: "form"}) do |f|%>
    
    <div class="form-group col-md-8">
      <p>
         <%= f.text_field :title%>
      </p>

      
      <p>
         <%= f.text_field :status%>
      </p>

      <p>
         <%= f.text_field :bug_type%>
      </p>

      <p>
         <%= f.text_field :creator_id, data: { numeric: true } %>
      </p>

      <p>
        <%= f.text_field :assignee_id, data: { numeric: true } %>
      </p>

      <p>
         <%= f.text_field :project_id, data: { numeric: true } %>
      </p>
      
     

      <p>
           <%= f.submit "Create Bug"%>
       </p>

       <%end%>

       
      
       </div>
</div>

app/views/bugs/index.html.erb
<div class="container">




<table class="table table-success table-striped">
  <tr>
     <th>Bug Title</th>
     <th>Bug Status</th>
     <th>Bug Type</th>
     
     <th>Bug Creator</th>
     <th>Bug Assignee</th>
  </tr>
  
  
  <% @b.each do |b|%>

  <tr>
     <td><%= b.title%></td>
     <td><%= b.status%></td>
     <td><%= b.bug_type%></td>
     <td><%= b.bug_creator.username%></td>
     <td><%= b.bug_assignee.username%></td>
     
     
   
     
     

     
  </tr>
  <%end%>
</table>

</div>

app/views/bugs/new.html.erb
<%= render 'form'%>

app/views/bugs/show.html.erb
<div class="container">




<table class="table table-striped">
  <tr align="center">
     <th>Bug Name</th>
  </tr>
<% obj.each do |b|%>

  <tr align="center">
     <td><%= link_to b.title, bug_path(b), :class => "btn btn-outline-info"%></td>
  </tr>
  <% end %> 
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BugTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>







  <body>
   <%= render 'shared/navigation'%>
   <% if notice %>
     <p class="alert alert-success"><%= notice %></p>
   <% end %>
   <% if alert %>
     <p class="alert alert-danger"><%= alert %></p>
   <% end %>

   <% flash.each do |type, msg| %>
    <div class="alert alert-info">
      <%= msg %>
    </div>
   <% end %>
   
      <%= yield %>
    
  </body>
</html>

app/views/pages/home.html.erb
<div class ="container">
    <% if current_user %>
     <h2><span class="badge rounded-pill bg-dark"><%= current_user.role%></span></h2>
      <h2>Welcome Back <%= current_user.username%></h2>


      <h1 align="center"><%= link_to "Users", users_path, :class => "btn btn-outline-primary"%></h1>
      <h1 align="center"><%= link_to "Projects", projects_path, :class => "btn btn-outline-danger"%></h1>
      <h1 align="center"><%= link_to "Bugs", bugs_path, :class => "btn btn-outline-warning"%></h1>
      <br>
     <br>
     <br>
     <br>
     <br>
     <br>
     <h1 align="center"><%= link_to "Create Project", new_project_path, :class => "btn btn-outline-primary"%></h1>





      <br>
      <br>
      <% if current_user.role == 'developer'%>
         <h1 align="center"><%= link_to "Check Assigned Projects", user_path(current_user.id), :class => "btn btn-outline-info"%></h1>
         <h1 align="center"><%= link_to "Check Assigned Bugs", user_path(current_user.id), :class => "btn btn-outline-info"%></h1>
      <% end %>
      <% if current_user.role == 'qa'%>
        <h1 align="center"><%= link_to "Check Assigned Projects", user_path(current_user.id), :class => "btn btn-outline-info"%></h1>
        <h1 align="center"><%= link_to "Check Created Bugs", user_path(current_user.id), :class => "btn btn-outline-info"%></h1>
      <% end %>
      <% if current_user.role == 'manager'%>
        <h1 align="center"><%= link_to "Check Created Projects", user_path(current_user.id), :class => "btn btn-outline-info"%></h1>
      <% end %>
      <hr>
      <h4 align="center">OR</h4>
      <nav class="navbar navbar-light bg-light">
       <form class="container-fluid justify-content-start">
       <button class="btn btn-outline-success me-2" type="button"><%= link_to "Log out!", destroy_user_session_path, 'data-turbo-method': :delete, :class => "btn"%></button>
      </form>
      </nav>
      
    <% else %>
      <h1>Welcome to Bug Tracker</h1>
   <nav class="navbar navbar-light bg-light">
    <form class="container-fluid justify-content-start">
      <button class="btn btn-outline-success me-2" type="button"><%= link_to "Sign up!", new_user_registration_path, :class => "btn" %></button>
      <button class="btn btn-sm btn-outline-secondary" type="button"><%= link_to "Log in!!", new_user_session_path, :class => "btn" %></button>
    </form>
   </nav>
    <% end %>
</div>

app/views/projects/_form.html.erb
<div class="container">
<%= bootstrap_form_for(@p, :html => {class: "form-horizontal", role: "form"}) do |f|%>
    
    <div class="form-group col-md-8">
      <p>
         <%= f.text_field :projectname%>
      </p>

      
      <p>
         <%= f.text_field :description%>
      </p>

      <p>
         <%= f.text_field :creator_id, data: { numeric: true } %>
      </p>

      <p>
      <%= f.text_field :assignee_id, data: { numeric: true } %>
   </p>
      
     

      <p>
           <%= f.submit "Create Project", data: {turbo: false}%>
       </p>

       <%end%>

       
      
       </div>
</div>

app/views/projects/_project.html.erb
<div class="container">




<table class="table table-striped">
<tr align="center">
     <th>Project Name</th>
    
  </tr>
<% obj.each do |p|%>

  <tr align="center">
     <td><%= link_to p.projectname, project_path(p), :class => "btn btn-outline-info"%></td>
     
  </tr>
  <% end %>  
</table>


    

</div>

app/views/projects/index.html.erb
<div class="container">




<table class="table table-success table-striped">
  <tr>
     <th>Project Name</th>
     <th>Description</th>
     <th>Project Creator</th>
     
     <th>Project Bugs</th>
  </tr>
  
  
  <% @p.each do |p|%>

  <tr>
     <td><%= p.projectname%></td>
     <td><%= truncate(p.description, length: 30)%></td>
     <td><%= p.project_creator.username%></td>
     
   
     
     <td><%= link_to "Bugs", project_path(p), :class => "btn btn-outline-info"%></td>

     
  </tr>
  <%end%>
</table>

</div>

app/views/projects/new.html.erb
<%= render 'form'%>

app/views/projects/show.html.erb
<div class="container">




<table class="table table-striped">
  <tr align="center">
     <th>Bug Name</th>
  </tr>
<% @p.bugs.each do |p|%>

  <tr align="center">
     <td><%= p.title%></td>
  </tr>
  <% end %> 
</table>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Bug Tracker</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/users/_user.html.erb
<div class="container">




<table class="table table-striped">
<tr align="center">
     <th>User Name</th>
    
  </tr>
<% obj.each do |u|%>

  <tr align="center">
     <td><%= u.username%></td>
     
  </tr>
  <% end %>  
</table>

app/views/users/index.html.erb
<div class="container">




<table class="table table-success table-striped">
  <tr>
     <th>User Name</th>
     
  </tr>
  
  
  <% @usr.each do |u|%>

  <tr>
     <td><%= u.username%></td>
     
   
   
     
     

     
  </tr>
  <%end%>
</table>

</div>

app/views/users/show.html.erb
<h2 align="center"><%= @usr.username%>'s Projects</h2>
<%= render 'projects/project', obj: @usr.projects%>

<% if current_user.role == 'developer'%>
  <h2 align="center"><%= @usr.username%>'s Assigned Bugs</h2>
  <%= render 'bugs/bug', obj: @usr.assigned_bugs%>
<%end%>

<% if current_user.role == 'qa'%>
   <h2 align="center"><%= @usr.username%>'s Created Bugs</h2>
   <%= render 'bugs/bug', obj: @usr.created_bugs%>
<%end%>